name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: bundle install
    - name: Download SwiftLint
      run: bundle exec fastlane download_swiftlint
    - name: Build
      run: bundle exec fastlane build
